<a href="https://colab.research.google.com/github/fedhafathimacc/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
array= np.random.randint(10,size=(3,3))
print(array)


[[9 8 0]
 [1 9 4]
 [4 5 1]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np
array1= np.random.randint(10,size=(4,4))
print(array1)
array2=np.random.randint(10,size=(4,4))
print(array2)
x=array1.reshape(2,8)
y=array2.reshape(2,8)
print (np.vstack((x,y)))
print (np.hstack((x,y)))

[[2 8 5 9]
 [2 6 9 9]
 [1 9 5 6]
 [1 4 2 7]]
[[8 9 7 3]
 [8 1 7 7]
 [2 2 0 6]
 [9 9 3 0]]
[[2 8 5 9 2 6 9 9]
 [1 9 5 6 1 4 2 7]
 [8 9 7 3 8 1 7 7]
 [2 2 0 6 9 9 3 0]]
[[2 8 5 9 2 6 9 9 8 9 7 3 8 1 7 7]
 [1 9 5 6 1 4 2 7 2 2 0 6 9 9 3 0]]
